# Generated by Django 5.0.1 on 2024-01-24 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=15)),
                ('capacity', models.IntegerField(default=20)),
                ('number_plate', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='bus_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('depart_loc', models.CharField(choices=[('1', 'Kathmandu'), ('2', 'Hetuada'), ('3', 'Tandi'), ('4', 'Inarwa'), ('5', 'Bharatpur'), ('6', 'Ithari'), ('7', 'Polkhara')], default='1', max_length=20)),
                ('arrive_loc', models.CharField(choices=[('1', 'Kathmandu'), ('2', 'Hetuada'), ('3', 'Tandi'), ('4', 'Inarwa'), ('5', 'Bharatpur'), ('6', 'Ithari'), ('7', 'Polkhara')], default='1', max_length=20)),
                ('distance', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('depart_date', models.DateTimeField()),
                ('bus_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.bus')),
                ('route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.route')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3)),
                ('is_free', models.BooleanField(blank=True, default=True)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_num', models.CharField(max_length=10)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.busschedule')),
                ('seat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.seat')),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cancelled', models.BooleanField(blank=True, default=False)),
                ('refunded', models.BooleanField(blank=True, default=False)),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('passenger', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True, default=1)),
                ('book_date', models.DateTimeField(blank=True)),
                ('depart_date', models.DateTimeField(blank=True)),
                ('depart_loc', models.CharField(blank=True, max_length=30)),
                ('arrive_loc', models.CharField(blank=True, max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('ticket_num', models.CharField(blank=True, max_length=10)),
                ('cost', models.IntegerField(blank=True, default=1)),
                ('bus', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='bus_reserve.bus')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('t_date', models.DateTimeField(auto_now_add=True)),
                ('pdix', models.CharField(blank=True, max_length=256, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bought_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('ticket_id', models.ManyToManyField(blank=True, to='bus_reserve.ticket')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.transactiontable')),
            ],
        ),
    ]
