# Generated by Django 4.2.9 on 2024-01-31 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=15)),
                ('capacity', models.IntegerField(default=20)),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='bus_images/')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('depart_date', models.DateTimeField()),
                ('bus_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.bus')),
            ],
            options={
                'verbose_name': 'Bus Schedule',
                'verbose_name_plural': 'Bus Schedules',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('depart_loc', models.CharField(choices=[('1', 'Kathmandu'), ('2', 'Hetuada'), ('3', 'Tandi'), ('4', 'Inarwa'), ('5', 'Narayangarh'), ('6', 'Ithari'), ('7', 'Pokhara'), ('8', 'Biratnagar')], default='1', max_length=20)),
                ('arrive_loc', models.CharField(choices=[('1', 'Kathmandu'), ('2', 'Hetuada'), ('3', 'Tandi'), ('4', 'Inarwa'), ('5', 'Narayangarh'), ('6', 'Ithari'), ('7', 'Pokhara'), ('8', 'Biratnagar')], default='1', max_length=20)),
                ('distance', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=3)),
                ('is_free', models.BooleanField(blank=True, default=True)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.bus')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_num', models.CharField(max_length=10)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.busschedule')),
                ('seat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.seat')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False)),
                ('t_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('pidx', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('1', 'Completed'), ('2', 'Refunded'), ('3', 'Cancelled')], default='1', max_length=20)),
                ('khalti_tran_id', models.CharField(blank=True, max_length=256)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bought_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('ticket_id', models.ManyToManyField(blank=True, to='bus_reserve.ticket')),
                ('transaction_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.transactiontable')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Order',
                'verbose_name_plural': 'Ticket Orders',
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=25)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('depart_loc', models.CharField(blank=True, max_length=25)),
                ('arrive_loc', models.CharField(blank=True, max_length=25)),
                ('price', models.IntegerField(blank=True, default=100)),
                ('depart_date', models.DateTimeField(blank=True)),
                ('bus_model', models.CharField(blank=True, max_length=25)),
                ('tran_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.transactiontable')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket History',
                'verbose_name_plural': 'Ticket Histories',
            },
        ),
        migrations.AddField(
            model_name='busschedule',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.route'),
        ),
    ]
