# Generated by Django 5.0.1 on 2024-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontable',
            name='pending',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='transactiontable',
            name='phone',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
