# Generated by Django 5.0.1 on 2024-01-13 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickethistory",
            name="depart_info_id",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="is_bought",
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="passenger_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="passenger_phone",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="bus_reserve.seat"
            ),
        ),
        migrations.AlterField(
            model_name="ticketorder",
            name="ticket_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="bus_reserve.ticket"
            ),
        ),
        migrations.CreateModel(
            name="TransactionTable",
            fields=[
                (
                    "id",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("t_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="transaction_id",
            field=models.ForeignKey(
                default="Refunded",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="bus_reserve.transactiontable",
            ),
        ),
        migrations.DeleteModel(
            name="DepartInfo",
        ),
        migrations.DeleteModel(
            name="TicketHistory",
        ),
    ]
