# Generated by Django 4.2.9 on 2024-02-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='price',
            field=models.FloatField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='amount',
            field=models.FloatField(default=100),
        ),
    ]
