# Generated by Django 5.0.1 on 2024-01-11 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticektorder",
            name="ticket_id",
        ),
        migrations.RemoveField(
            model_name="ticektorder",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="bus",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("03f96360-e854-43d2-a182-a5f57f3e4bf7"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="busschedule",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c683d0ac-616c-44c3-b6a8-d57dbd365714"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="departinfo",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b052e680-057a-4731-a3a7-893e6a1aa653"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9c067720-93be-45d7-993d-ef212ba91867"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5404688b-44b5-4c84-a999-d18cdaef6a06"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c5147f06-e53c-4c6b-8e4b-9949f2e1ff94"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="TicketHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("f3964692-499e-4d21-b8c1-c9095fbb41ef"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cancelled", models.BooleanField(blank=True, default=False)),
                ("refunded", models.BooleanField(blank=True, default=False)),
                (
                    "depart_info_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_reserve.departinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("5c999c3f-7ede-4833-8311-5aec42eec58c"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bought_date", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_reserve.ticket",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="departinfo",
            name="ticket_order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_reserve.ticketorder",
            ),
        ),
        migrations.DeleteModel(
            name="TicektHistory",
        ),
        migrations.DeleteModel(
            name="TicektOrder",
        ),
    ]
