# Generated by Django 5.0.1 on 2024-01-11 05:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0002_remove_ticektorder_ticket_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("738c1416-479c-4e8e-b54a-e1cc9395846e"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="busschedule",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("3961a12c-62ff-4f3d-9a6c-8c47ff63d843"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="departinfo",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("d0a3d10d-12f4-44f9-a20c-5082230080e1"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("1747a984-dbea-4481-9102-82bc528742e4"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("878c63e2-3594-416a-ad50-0fefc9d63d88"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("b74360e9-2b62-446e-8fed-24b9060cb986"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tickethistory",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("8f844715-7ab1-4f8f-bc8b-2430b279d928"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="ticketorder",
            name="id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("c2a69d75-7220-4fa7-a071-de5cde673f93"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
