# Generated by Django 5.0.1 on 2024-01-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0002_transactiontable_pending_transactiontable_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontable',
            name='pending',
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='pending',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
