# Generated by Django 4.2.9 on 2024-02-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0002_alter_route_distance_alter_route_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_free',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_bought',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='bus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.bus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.seat'),
        ),
    ]
