# Generated by Django 5.0.1 on 2024-01-13 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0002_remove_tickethistory_depart_info_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("passenger_arrived", models.BooleanField(default=False)),
                ("bus_problem", models.BooleanField(default=False)),
                (
                    "ticket_order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_reserve.ticketorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cancelled", models.BooleanField(blank=True, default=False)),
                ("refunded", models.BooleanField(blank=True, default=False)),
                ("user_id", models.CharField(blank=True, max_length=200)),
                ("passenger", models.CharField(max_length=30)),
                ("phone", models.IntegerField(blank=True, default=1)),
                ("book_date", models.DateTimeField(blank=True)),
                ("depart_date", models.DateTimeField(blank=True)),
                ("depart_loc", models.CharField(blank=True, max_length=30)),
                ("arrive_loc", models.CharField(blank=True, max_length=30)),
                ("transaction_id", models.CharField(blank=True, max_length=200)),
                ("ticket_num", models.CharField(blank=True, max_length=10)),
                ("cost", models.IntegerField(blank=True, default=1)),
                (
                    "bus",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bus_reserve.bus",
                    ),
                ),
            ],
        ),
    ]
