# Generated by Django 5.0.1 on 2024-01-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0003_remove_transactiontable_pending_ticketorder_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='bought_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
