# Generated by Django 5.0.1 on 2024-01-11 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0003_alter_bus_id_alter_busschedule_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="busschedule",
            name="id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="departinfo",
            name="id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tickethistory",
            name="id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ticketorder",
            name="id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
