# Generated by Django 5.0.1 on 2024-01-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0003_departinfo_tickethistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DepartInfo",
        ),
    ]
