# Generated by Django 5.0.1 on 2024-01-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0004_alter_bus_id_alter_busschedule_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="arrive_loc",
            field=models.CharField(
                choices=[
                    (1, "Kathmandu"),
                    (2, "Hetuada"),
                    (3, "Tandi"),
                    (4, "Inarwa"),
                    (5, "Bharatpur"),
                    (6, "Ithari"),
                    (7, "Polkhara"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="depart_loc",
            field=models.CharField(
                choices=[
                    (1, "Kathmandu"),
                    (2, "Hetuada"),
                    (3, "Tandi"),
                    (4, "Inarwa"),
                    (5, "Bharatpur"),
                    (6, "Ithari"),
                    (7, "Polkhara"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
