# Generated by Django 5.0.1 on 2024-01-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0005_remove_ticketorder_passenger_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="busschedule",
            old_name="datetime",
            new_name="depart_date",
        ),
    ]
