# Generated by Django 5.0.1 on 2024-01-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0005_alter_transactiontable_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontable',
            name='amount',
            field=models.IntegerField(default=100),
        ),
    ]
