# Generated by Django 5.0.1 on 2024-01-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0005_route_arrive_loc_alter_route_depart_loc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="arrive_loc",
            field=models.CharField(
                choices=[
                    ("1", "Kathmandu"),
                    ("2", "Hetuada"),
                    ("3", "Tandi"),
                    ("4", "Inarwa"),
                    ("5", "Bharatpur"),
                    ("6", "Ithari"),
                    ("7", "Polkhara"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="depart_loc",
            field=models.CharField(
                choices=[
                    ("1", "Kathmandu"),
                    ("2", "Hetuada"),
                    ("3", "Tandi"),
                    ("4", "Inarwa"),
                    ("5", "Bharatpur"),
                    ("6", "Ithari"),
                    ("7", "Polkhara"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
