# Generated by Django 5.0.1 on 2024-01-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0006_rename_datetime_busschedule_depart_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketorder",
            name="ticket_id",
        ),
        migrations.RemoveField(
            model_name="ticketorder",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="ticketorder",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.DeleteModel(
            name="TicketOrder",
        ),
    ]
