# Generated by Django 5.0.1 on 2024-01-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0007_transactiontable_status_alter_ticketorder_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='pending',
        ),
    ]
