# Generated by Django 5.0.1 on 2024-01-18 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_reserve", "0007_remove_ticketorder_ticket_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticket_num", models.CharField(max_length=10)),
                ("bought_date", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_reserve.busschedule",
                    ),
                ),
                (
                    "seat_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_reserve.seat",
                    ),
                ),
                (
                    "transaction_id",
                    models.ForeignKey(
                        default="Refunded",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="bus_reserve.transactiontable",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
