# Generated by Django 5.0.1 on 2024-01-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0008_remove_ticketorder_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontable',
            old_name='pdix',
            new_name='pidx',
        ),
    ]
