# Generated by Django 5.0.1 on 2024-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0009_rename_pdix_transactiontable_pidx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='status',
            field=models.CharField(choices=[('1', 'Completed'), ('2', 'Refunded')], default='1', max_length=20),
        ),
    ]
