# Generated by Django 5.0.1 on 2024-01-22 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0009_remove_ticket_bought_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='ticket_id',
            field=models.ManyToManyField(blank=True, to='bus_reserve.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='transaction_id',
            field=models.ForeignKey(blank=True, default='Refunded', on_delete=django.db.models.deletion.SET_DEFAULT, to='bus_reserve.transactiontable'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
