# Generated by Django 5.0.1 on 2024-01-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0010_alter_ticketorder_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='bus_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.bus'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='transaction_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.transactiontable'),
        ),
    ]
