# Generated by Django 5.0.1 on 2024-01-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0011_transactiontable_khalti_tran_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontable',
            name='khalti_tran_id',
        ),
    ]
