# Generated by Django 5.0.1 on 2024-01-24 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0011_alter_busschedule_bus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontable',
            name='pdix',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontable',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
