# Generated by Django 5.0.1 on 2024-01-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0012_remove_transactiontable_khalti_tran_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontable',
            name='khalti_tran_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
