# Generated by Django 4.2.9 on 2024-01-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0013_transactiontable_khalti_tran_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketHistory',
        ),
    ]
