# Generated by Django 4.2.9 on 2024-01-26 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_reserve', '0014_delete_tickethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='status',
            field=models.CharField(choices=[('1', 'Completed'), ('2', 'Refunded'), ('3', 'Cancelled')], default='1', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=25)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('depart_loc', models.CharField(blank=True, max_length=25)),
                ('arrive_loc', models.CharField(blank=True, max_length=25)),
                ('price', models.IntegerField(blank=True, default=100)),
                ('depart_date', models.DateTimeField(blank=True)),
                ('bus_model', models.CharField(blank=True, max_length=25)),
                ('tran_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.transactiontable')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
