# Generated by Django 4.2.9 on 2024-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0015_alter_transactiontable_status_tickethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontable',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
