# Generated by Django 4.2.9 on 2024-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0016_alter_transactiontable_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='busschedule',
            options={'verbose_name': 'Bus Schedule', 'verbose_name_plural': 'Bus Schedules'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Seat', 'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'verbose_name': 'Ticket History', 'verbose_name_plural': 'Ticket Histories'},
        ),
        migrations.AlterModelOptions(
            name='ticketorder',
            options={'verbose_name': 'Ticket Order', 'verbose_name_plural': 'Ticket Orders'},
        ),
        migrations.AlterModelOptions(
            name='transactiontable',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrive_loc',
            field=models.CharField(choices=[('1', 'Kathmandu'), ('2', 'Hetuada'), ('3', 'Tandi'), ('4', 'Inarwa'), ('5', 'Narayangarh'), ('6', 'Ithari'), ('7', 'Pokhara'), ('8', 'Biratnagar')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='depart_loc',
            field=models.CharField(choices=[('1', 'Kathmandu'), ('2', 'Hetuada'), ('3', 'Tandi'), ('4', 'Inarwa'), ('5', 'Narayangarh'), ('6', 'Ithari'), ('7', 'Pokhara'), ('8', 'Biratnagar')], default='1', max_length=20),
        ),
    ]
