# Generated by Django 4.2.9 on 2024-01-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0017_alter_bus_options_alter_busschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='bus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.bus'),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.route'),
        ),
    ]
