# Generated by Django 4.2.9 on 2024-01-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reserve', '0018_alter_busschedule_bus_id_alter_busschedule_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='bus_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus_reserve.bus'),
        ),
    ]
